### ISSUE TITLE
Can add items to cart without selecting required modifiers

### ISSUE THREAD

**Issue by jason-finestone** [ordrup/infrastructure-actions#11]
See video of menu client being able to add item to cart without selecting the required mod. 

Menu builder screenshot below video showing Burrito Size mod as required.

https://images.zenhubusercontent.com/262458950/a94c4572-83fa-4ab7-90ff-1d34cd036ca2/can_add_item_to_cart_w_out_required_mods.mov

![Screen Shot 2021-11-04 at 11.01.56 PM.png](https://images.zenhubusercontent.com/5f2c41278a73157fdf80e200/67224310-3a3d-406b-bbb9-6d7f5104397f)

**Comment by merrickread** [comment]
closed for duplicate, this ones in the wrong repo
